### ISSUE TITLE
Unclear experiment

### ISSUE THREAD

**Issue by Ldaxar** [Sindt/UFO#4]
Hey,

There is no clear explanation of Hyper-V problem.

Is it a common issue? Maybe it's something wrong with your machine.

Does "bsod" appears after running provisioning script on any kind of Windows? Can reader of this article reproduce this problem on Windows XP,7,8,10 etc?

You should also include information about your set up (windows version, vagrant version, provisioning script) to make experiment reproducible.

**Comment by Sindt** [comment]
The blog actually states the inforamtion about when the BSOD apperars:

**Expected behavior:**
Run Vagrant up, Virtual machine should be running

**Actual behavior:**
Blue Screen of death, after repairing disk it returns this error:

“There was an error while executing VBoxManage, a CLI used by Vagrant for controlling VirtualBox. The command and stderr is shown below.”

So, after you as a developer tries to google the error, we found out the Hyper-V in windows 8 and higher is the culprit! 


It says clearly that it happens when running vagrant up, and its happening because of the hyper-v in windows 8 and higher.
